language: android
jdk: oraclejdk8
cache:
- bundler
android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.2
  - android-24
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-18
before_install:
- rvm install ruby-2.3.0
- openssl aes-256-cbc -K $encrypted_a318a1fa7ccb_key -iv $encrypted_a318a1fa7ccb_iv
  -in deployment_key.gpg.enc -out deployment_key.gpg -d
install:
- bundle install
before_script:
- echo no | android create avd --force -n test -t android-18 --abi armeabi-v7a
- emulator -avd test -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82
script:
- bundle exec fastlane ci
env:
  global:
  - secure: DqwX6XYoFUqe/K+sgRGzr3qN/Rejc3+Gtis8PJMhiV4jl7zv844lgLLwNfvZM5NLmTzkEPv5FZibmLmfrueX9MmZ4mFKQPFelPPct6U0JRihcDQNS+QNtLdXSCCj+b/w/5Qj/elcq9CHEzduNv1+5p4yLjWCJcl5JA9hCWOrg0+30eE8aj2MoPrVG29KaF617iO7oyBf4L3IfKdtASXTnd3aKuzWyzJKnhNd+PbVzN+MP4KxajzYOr1M0DVGNpz4VFekKoegKYWP92bppS6tEQu40uYnGMuWQZQ/m4X+uYNybiIPLY5atIjYzTtIxWmJ0mMaBbGtRpHHDzJI20qOUbJHhk8GxLs/9WfWHq+3f0pZaKg23e8583HLwYSpONQXlqjtAOIecMDMC3SCAWixEmZoRmKTaL9gUXL/g3USOvdNZ26hph2KsH3wk7Kcpzfyis8+LX6hzCzHXXQif7CLTZDjswHavkO3lMnvI1ePn4n9g9Bm84rywXQhjcgJqxasWhrsdvnVVkxi/IWrDmRnrTAAdkwMFTMs0j+g84OIi6yggB1AAEbsFZ/6wR0mKaWyoSRxNL3n1jE4g9ASis8VyMr6cHAMktoC+scJfcpiMGlR6JXvHg3EpS888BbIU4gxX5wYCoXNe8F0J5ravNPsIZq74UHpJyWuLxDZmU8iwGA=
  - secure: nWyDJeDmQlT83HClY89VWTWyPZ58cgrlBU1uVruvTNr3p6HAm09RsyzcBSxOY2vLnI2kmP6A3L8ScQQKojae0FavfX5JtEG/EGeFIXJ5U5NPoPuyTOanxkhwiB5+3DnsNdXRnTtsw0W2RdS+q12CZqf0XYVX1Q3EmtfcHSuvEviy1xo6+H3CDTkNep2rDI+H05zTJEOFBH78Bm3ip54zUOy9GZMJ2ZVS6wxy3G/0rz7ZmqPQ6tWhcZ4hfjXbxFujBU5PQEMepjV0RlNeA5grfEg16iWEsiUT1Zalyme7O3cY167r0Q2QSViO1I1Z6lJjcA0SiqJl9EMTYFIrRE5eMjwLq96VkZZDWqS9B4eZjPWK9TPSL3kdTRGKwu0Aqr7N3ltp3op6kI9cr+LzwSRdh8bE15MKYfCafCL4EoUjd4kJTCq4nuSJo2y0fNdq5PugcZorqo0W8BkQlLryzDNY+aZKlnJJiGgW+EoNwg5G1PaJnpVjt3HKVE1i+gFkhsIQ2kBW57SqyFhnYrzW7dukf6H/GAfcWII6jLR+iTjurwoCTAOxST8gUqHN6hpP62IshMAztgwH29UNhQ1O/2O2iWVRd5Hh1Hq3HLFpAikCEN/DVwXFxiZoQrsLnL8MCMcogsW64cyuAexE4C4VIT5DcMFnxWjRegJCLhbDnr/aAiw=
  - secure: VawkjU2IfGPX2oBeOSZhsImrZTV4kAYe0K1itU/Ph4jIZ7fsKk6RVyXq5GO4l0Ul4UCaI2UpeYok98vHKb4E4X+u9ECjIYB9cH7E9yLF20t+KseyyQT45vpM7ZaSDQQjwjuhVq9BtW/ayZ8q3oJfN8fAhox5tl4SGHRlr+ANicNkoxOLsjM9O0t7KudJY7qU8mRe4/UMnMDQZ3EJI0/JuGENTqtsZhfB2eHpntrIWrC7yVv3aJG/aXUS1pJ4stY/48ZPlHZCXWJ3R28w8UTUtgHkca0KveC3hEGnreU323Zcz6ju0+ilF5bkvMUR7L+AmBa5qwl/rahN0dZsHorMBXpiZ3srj3bSMOuX/FOfcSV3/ogP+HREMthRrJReHbLDlg7z6ZJzZNvJWYF/eylwmIIVnhl5ikooeppIi+Dtom+3QjGD5AixrxINt5vq+klnUn3nQOI72nRk3gX39MgilPAdZfp0vnt6+ixfZj1Xe1Rx2gmDxcXQdDWIO6u04zKdMH/7kz90zG3DRKGfkIJd14ZW1XdmjA/XKWIiXkWjL493LrAdnytwLM3hcDY12zpVeAuk/Vom0bX8uExESfpeCRXe87OFHYFuk/IBFduzfI+gVmFBf9jRQcShkJrhnKWsqT2QZptNZilJ8jtO8gMPuweRW0CBAIPH63wreF6i6d4=
  - secure: rR2RmAYDnyLUBan8A07WH+yM6xEezBIv36rqcNe+cwh1YnE3piycOJVubyb8fSMMazXmoS4nFtHxt4W/1D33xukv1d6JZO+gsK6fLkOkVtDjqe4xypnxSrAucUN/UIfj9Mqk8qWTQ1tiqgJ80KA6O0FemLcFS/WEiB48+O5EA5mDQ0v3PrEQnW+ydS+C0frouDd7WVkIJBGpw1wfZVkNNYVVehUnYiuo0LWbSSbh8IQYqJRhtJCb8MQG2yoGDnStxtja+F9+ElG3R1GuslazdXh6sHVeReodmF3Q0C8taurv6zH8fazw4bd3lwUKnKM3i84CZpymUDNqb6v6SPbnYSfqoe8b4RcvSZ8nalFuwUTcnHm6lk7JjSdmGNhL0HoNyzJ4qbvsHY/+1eZr8sQxn9yzQPrhChkDXi7Srxb9XGCrrAm/L+hubVnv0ia0JWWLCWTrmkZEa2ZxAm22sDfTTrbYu0TxK3PQl61AJKiBPWHFT+wT2cN/bn6WJICvjQXK1OE5weUduT9MhnglIeW/bkK1pJaqvD+jBxjsmnxvWgPHW+YluvHX/tuCSKmiaT6W1WzB7zNUmB7/hrjcRN13okzMbjP7Uzo2k7jLDNBuLneXE3hr+i91pZDfyMsgYlsEEs2sczI401AJlYwO4u260JCs2Id6dEVrqbXbWniG0VI=
notifications:
  slack:
    secure: ATJ4HJJFUUwArUaWc6cxpbYvkPKMs/jicXg1wW15WD7Q8tKlRE1I5OcGnC5w9519DayWPiRclbK973iwXTNMVRt0wQJpB01ffFVjEIZMU6rlW1iDVuzT/vauQHnNndowGQiCRk4rk8y+XWBD+In0dKVXJbj+q8GPBRQk4LO8GWXGp58v+uQRW2vGkH83kxaCH6Z2u4OW+MbInIJr7l55S0Hf4BRu3x9YKWzkiV4WAeBWgULt6lnRzI/xyaRfDHl51+Ay7K3pfLZ/7VNRsI2DdiuA1UQ5hytlHrInL3610huY/D/HlOGVaFL+8wlR2QNrLA+Z9HEezPSHd7vFo9EwXSGzejkLps1mT9kN4Lie1nEkTcn7sQJQGgZtthz/DqcOmCC1yk4jEr6wseMKbiN75BwZMYMQhoyGqu3FdUf8obg3czRdKCeRx9aVXH6XFwRQ41Wtt4oA5dEDKCf4TwL/TifgTRePOZ/r4sArg2lgLuj4p+B3vfJyOjAHiD2D/QxyDhecq+w5Ssd95iIfwfQ9rM7Rv3wB+ogpWbr3x4uEdA89aZ/dLoQc3eXQ8bgEPqYqdlnea2vaoLlx7cP1lYyjedeiKN2nJx84orENYdy+kzTHT/ViIX/eksVMPPwsHYywTrGclU7H2XA/yhdpfsoNVO4r5fcUvF6U5A1Qg6507Ok=
